### ISSUE TITLE
Add resources

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/inferential-stats-course#3]
I'm going to add any resources I come across that make sense in the Learn More sections of lessons.

https://drmowinckels.io/blog/2020-06-24-the-linear-regression-family-in-r/

**Comment by danawanzer** [comment]
I created a blank "Your Turn" Rmd that people can use instead of creating a blank Rmd file. It's in the Github, but I don't know how you want to link to it on the course.

**Comment by danawanzer** [comment]
Finished all the rest of the Learn More components in the course. Feel free to add more!

**Comment by dgkeyes** [comment]
Just realized I never responded. These look great. I'll let you know if I have any questions as I'm working through them.

**Comment by danawanzer** [comment]
Sounds great!!
